USE [Linerath-Blog]
GO

INSERT INTO [dbo].[Articles]
           ([Title], [Body], [CreationDate])
     VALUES
           (N'Welcome', N'To my in-development blog. I''m so excited about that idea.', '20181231 06:00:00 PM')
          ,(N'Slipknot - Eyeless', N'Insane - Am I the only motherfucker with a brain?' + CHAR(13) + 'I''m hearing voices but all they do is complain' + CHAR(13) + 'How many times have you wanted to kill' + CHAR(13) + 'Everything and everyone - Say you''ll do it but never will' + CHAR(13) + 'You can''t see California without Marlon Brando''s eyes' + CHAR(13) + CHAR(13) + 'Can''t see California without Marlon Brando''s eyes' + CHAR(13) + 'You can''t see California without Marlon Brando''s eyes', '20181231 06:00:00 PM')
          ,(N'A', N'The show must go on.', '20190113 02:00:00 PM')
          ,(N'Haha', N'Money, money, money. Always sunny.', '20190113 03:00:00 PM')
		  ,(N'I''m A Marionette', N'"You''re so free," that''s what everybody''s telling me' + CHAR(13) + 'Yet I feel I''m like an outward-bound, pushed around, refugee' + CHAR(13) + 'Something''s wrong, got a feeling that I don''t belong' + CHAR(13) + 'As if I had come from outer space, out of place, like King Kong' + CHAR(13) + CHAR(13) + CHAR(13) + 'I''m a marionette, just a marionette, pull the string' + CHAR(13) + 'I''m a marionette, everybody''s pet, just as long as I sing' + CHAR(13) + 'I''m a marionette, see my pirouette, round and round' + CHAR(13) + 'I''m a marionette, I''m a marionette, just a silly old clown' + CHAR(13) + CHAR(13) + CHAR(13) + 'Like a doll, like a puppet with no will at all' + CHAR(13) + 'And somebody told me how to talk, how to walk, how to fall' + CHAR(13) + CHAR(13) + CHAR(13) + 'Can''t complain, I''ve got no-one but myself to blame' + CHAR(13) + 'Something''s happening I can''t control, lost my hold, is it safe?' + CHAR(13) + CHAR(13) + CHAR(13) + 'I''m a marionette, just a marionette, pull the string' + CHAR(13) + 'I''m a marionette, everybody''s pet, just as long as I sing' + CHAR(13) + 'I''m a marionette, see my pirouette, round and round' + CHAR(13) + 'I''m a marionette, I''m a marionette, just a silly old clown' + CHAR(13) + CHAR(13) + CHAR(13) + '"Look this way, just a little smile," is what they say' + CHAR(13) + '"You look better on the photograph if you laugh, that''s okay"' + CHAR(13) + CHAR(13) + CHAR(13) + 'I''m a marionette, just a marionette, pull the string' + CHAR(13) + 'I''m a marionette, everybody''s pet, just as long as I sing' + CHAR(13) + 'I''m a marionette, see my pirouette, round and round' + CHAR(13) + 'I''m a marionette, I''m a marionette, just a silly old clown' + CHAR(13) + CHAR(13) + CHAR(13) + '"You''re so free," that''s what everybody''s telling me' + CHAR(13) + 'Yet I feel I''m like an outward-bound, pushed around, refugee.', '20190115 08:41:00 AM')
		  ,(N'Still Alive', N'This was a triumph.'+ CHAR(13) + 'I''m making a note here:'+ CHAR(13) + 'HUGE SUCCESS.'+ CHAR(13) + 'It''s hard to overstate my satisfaction.'+ CHAR(13)+ CHAR(13) + 'Aperture Science.'+ CHAR(13) + 'We do what we must because we can.'+ CHAR(13) + 'For the good of all of us'+ CHAR(13) + 'Except the ones who are dead.'+ CHAR(13)+ CHAR(13) + 'But there''s no sense crying over every mistake.'+ CHAR(13) + 'You just keep on trying till you run out of cake.'+ CHAR(13) + 'And the science gets done and you make a neat gun.'+ CHAR(13) + 'For the people who are still alive.'+ CHAR(13) + 'I''m not even angry.'+ CHAR(13)+ CHAR(13) + 'I''m being so sincere right now.'+ CHAR(13) + 'Even though you broke my heart and killed me.'+ CHAR(13) + 'And tore me to pieces.'+ CHAR(13) + 'And threw every piece into a fire.'+ CHAR(13) + 'As they burned it hurt because'+ CHAR(13) + 'I was so happy for you!'+ CHAR(13)+ CHAR(13) + 'Now these points of data make a beautiful line.'+ CHAR(13) + 'And we''re out of beta, we''re releasing on time.'+ CHAR(13) + 'So I''m GLaD I got burned.'+ CHAR(13) + 'Think of all the things we learned'+ CHAR(13) + 'For the people who are still alive.'+ CHAR(13)+ CHAR(13) + 'Go ahead and leave me.'+ CHAR(13) + 'I think I prefer to stay inside.'+ CHAR(13) + 'Maybe you''ll find someone else to help you.'+ CHAR(13) + 'Maybe Black Mesa...'+ CHAR(13) + 'THAT WAS A JOKE. Haha. FAT CHANCE.'+ CHAR(13) + 'Anyway, this cake is great.'+ CHAR(13) + 'It''s so delicious and moist.'+ CHAR(13)+ CHAR(13) + 'Look at me still talking when there''s science to do.'+ CHAR(13) + 'When I look out there it makes me GLaD I''m not you.'+ CHAR(13) + 'I''ve experiments to run there is research to be done'+ CHAR(13) + 'On the people who are still alive'+ CHAR(13)+ CHAR(13) + 'And believe me I am still alive.'+ CHAR(13) + 'I''m doing science and I''m still alive.'+ CHAR(13) + 'I feel FANTASTIC and I''m still alive.'+ CHAR(13) + 'While you''re dying I''ll be still alive.'+ CHAR(13) + 'And when you''re dead I will be still alive.'+ CHAR(13)+ CHAR(13) + 'Still alive', '20190129 05:26:00 PM')
GO
